name: Release

on:
  workflow_run:
    workflows: [Lint and Test]
    types:
      - completed
  push:
    tags:
      - v*

jobs:
  release:
    if: ${{ contains('refs/tags', github.ref) == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/workflows/install

      - name: Release
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
