name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/workflows/install

      - name: Publish
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
