name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install
        uses: ./.github/workflows/install

      - name: Lint and test
        run: |
          pnpm clean
          pnpm build
          pnpm run-all-checks
          npm pack
          pnpm attw
          pnpm test
          pnpm test:build
          pnpm test-typing
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [dev, prod]
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install
        uses: ./.github/workflows/install

      - name: E2E Tests (${{ matrix.mode }})
        env:
          E2E_MODE: ${{ matrix.mode }}
        run: |
          pnpm clean
          pnpm build
          if [ "${{ matrix.mode }}" = "prod" ]; then
            pnpm build:e2e
          fi
          pnpm test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: playwright-report-${{ matrix.mode }}
          path: test/e2e/playwright-report
